from __future__ import annotations

import json
from pathlib import Path
from typing import Any


class HistoryError(RuntimeError):
    """Raised when a previous output cannot be used as conversation history."""


def latest_output_json(output_dir: Path) -> Path:
    candidates = sorted(output_dir.glob("*.json"), key=lambda path: path.stat().st_mtime, reverse=True)
    if not candidates:
        raise HistoryError(f"No JSON outputs found in: {output_dir}")
    return candidates[0]


def load_conversation_messages(output_json_path: Path) -> list[dict[str, Any]]:
    if not output_json_path.exists():
        raise HistoryError(f"Continuation file does not exist: {output_json_path}")

    data = json.loads(output_json_path.read_text(encoding="utf-8"))

    conversation_messages = _get_nested_messages(data, "conversation")
    if conversation_messages:
        return conversation_messages

    request_messages = _get_nested_messages(data, "request")
    if request_messages:
        assistant_message = assistant_message_from_response(data.get("response", {}))
        return [*request_messages, assistant_message]

    legacy_messages = _load_legacy_markdown_messages(output_json_path)
    if legacy_messages:
        return legacy_messages

    raise HistoryError(
        "Could not reconstruct conversation history. "
        "Use an output generated by the current pipeline, or pass a newer --continue-from JSON file."
    )


def assistant_message_from_response(response: dict[str, Any]) -> dict[str, Any]:
    choices = response.get("choices") or []
    if not choices:
        return {"role": "assistant", "content": ""}

    raw_message = choices[0].get("message") or {}
    message: dict[str, Any] = {
        "role": "assistant",
        "content": _normalize_content(raw_message.get("content", "")),
    }

    reasoning_content = raw_message.get("reasoning_content")
    if reasoning_content:
        message["reasoning_content"] = str(reasoning_content)

    tool_calls = raw_message.get("tool_calls")
    if tool_calls is not None:
        message["tool_calls"] = tool_calls

    return message


def _get_nested_messages(data: dict[str, Any], key: str) -> list[dict[str, Any]]:
    section = data.get(key)
    if not isinstance(section, dict):
        return []

    raw_messages = section.get("messages")
    if not isinstance(raw_messages, list):
        return []

    messages = [_sanitize_message(item) for item in raw_messages]
    return [message for message in messages if message]


def _sanitize_message(raw_message: Any) -> dict[str, Any] | None:
    if not isinstance(raw_message, dict):
        return None

    role = raw_message.get("role")
    if role not in {"system", "user", "assistant", "tool"}:
        return None

    message: dict[str, Any] = {"role": role}
    message["content"] = _normalize_content(raw_message.get("content", ""))

    if role == "assistant":
        reasoning_content = raw_message.get("reasoning_content")
        if reasoning_content:
            message["reasoning_content"] = str(reasoning_content)

        tool_calls = raw_message.get("tool_calls")
        if tool_calls is not None:
            message["tool_calls"] = tool_calls

    if role == "tool" and raw_message.get("tool_call_id"):
        message["tool_call_id"] = str(raw_message["tool_call_id"])

    if raw_message.get("name"):
        message["name"] = str(raw_message["name"])

    return message


def _load_legacy_markdown_messages(output_json_path: Path) -> list[dict[str, Any]]:
    markdown_path = output_json_path.with_suffix(".md")
    if not markdown_path.exists():
        return []

    text = markdown_path.read_text(encoding="utf-8", errors="replace")
    prompt = _extract_markdown_section(text, "## Prompt", "## Answer")
    answer = _extract_markdown_section(text, "## Answer", "## Reasoning")
    reasoning = _extract_markdown_section(text, "## Reasoning", None)
    if not prompt or not answer:
        return []

    messages: list[dict[str, Any]] = [
        {"role": "user", "content": prompt},
        {"role": "assistant", "content": answer},
    ]
    if reasoning and not reasoning.startswith("(No reasoning_content returned"):
        messages[-1]["reasoning_content"] = reasoning
    return messages


def _extract_markdown_section(text: str, start_marker: str, end_marker: str | None) -> str:
    start = text.find(start_marker)
    if start == -1:
        return ""

    start += len(start_marker)
    end = text.find(end_marker, start) if end_marker else -1
    section = text[start:] if end == -1 else text[start:end]
    return section.strip()


def _normalize_content(content: Any) -> Any:
    if content is None:
        return ""
    if isinstance(content, (str, list)):
        return content
    return str(content)
